// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ippnnvrjzkggmhtlzdiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwcG5udnJqemtnZ21odGx6ZGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDI1NjMsImV4cCI6MjA2NTgxODU2M30.WGuG4GFIuKUjJwIY6skVT5CmZd4g_SvodXZ4ZuZ3XQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);